name = "giacomocavalieri"
version = "1.0.0"
description = "My personal blog"

[dependencies]
gleam_stdlib = ">= 0.40.0 and < 1.0.0"
simplifile = ">= 2.1.0 and < 3.0.0"
lustre = ">= 5.2.1 and < 6.0.0"
gleam_time = ">= 1.4.0 and < 2.0.0"
frontmatter = ">= 1.0.1 and < 2.0.0"
tom = ">= 2.0.0 and < 3.0.0"
temporary = ">= 1.0.0 and < 2.0.0"
filepath = ">= 1.1.2 and < 2.0.0"
jot = ">= 7.1.0 and < 8.0.0"
gleam_json = ">= 3.1.0 and < 4.0.0"
lustre_dev_tools = ">= 2.3.4 and < 3.0.0"

[dev-dependencies]
